import { c as create_ssr_component, d as add_attribute } from "../../../chunks/ssr.js";
const fotnepWebsite = "/_app/immutable/assets/fotonep-site.CXLLmKbU.webp";
const investWebsite = "/_app/immutable/assets/bm-invest-website.BdiIdUok.webp";
const klikrWebsite = "/_app/immutable/assets/klikr-website.B-0AI7Yh.webp";
const carsWebsite = "/_app/immutable/assets/carsbytes-website.GbgCcZrG.webp";
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `<section class="flex flex-col space-y-12 max-w-6xl" data-svelte-h="svelte-1cmhf9s"> <div class="relative flex justify-center gap-3 items-center rounded-r-xl"><div class="absolute w-full h-full -bottom-4 left-12 rounded-xl border-4 border-lime-300 -z-10"></div> <img${add_attribute("src", fotnepWebsite, 0)} alt="fotonepremicnine.si website" width="480px" height="235px" class="object-cover object-center aspect-video rounded-xl"> <div class="flex flex-col prose max-w-none prose-h2:text-slate-200 prose-h2:tracking-wide prose-p:text-slate-300 prose-a:text-slate-400 prose-a:w-fit px-3 py-6"><h2>Real estate photography website</h2> <p>I&#39;ve build this website for my photography business, but I&#39;m planning to shut it down as
				there&#39;s low demand for these kind of services in my country. It&#39;s a single page website
				build in Svelte and TailwindCSS.</p> <a href="https://fotonepremicnine.si" target="_blank">Visit the site</a></div></div>  <div class="relative flex justify-center gap-3 items-center rounded-r-xl"><div class="absolute w-full h-full -bottom-4 right-12 rounded-xl border-4 border-lime-300 -z-10"></div> <img${add_attribute("src", investWebsite, 0)} alt="fotonepremicnine.si website" width="480px" height="235px" class="object-cover object-center aspect-video rounded-xl order-2"> <div class="flex flex-col prose max-w-none prose-h2:text-slate-200 prose-h2:tracking-wide prose-p:text-slate-300 prose-a:text-slate-400 prose-a:w-fit px-3 py-6"><h2>Authentication app</h2> <p>I&#39;m still building this portal for my friends and family to check their portfolios. The
				authentication is working. Try it. <i class="text-slate-400">(username: marko, password: testing123)</i>. This website is build in Sveltekit and TailwindCSS with Lucia Auth and Turso.</p> <a href="https://bm-investments.netlify.app/" target="_blank">Visit the site</a></div></div>  <div class="relative flex justify-center gap-3 items-center rounded-r-xl"><div class="absolute w-full h-full -bottom-4 left-12 rounded-xl border-4 border-lime-300 -z-10"></div> <img${add_attribute("src", klikrWebsite, 0)} alt="fotonepremicnine.si website" width="480px" height="235px" class="object-cover object-center aspect-video rounded-xl"> <div class="flex flex-col prose max-w-none prose-h2:text-slate-200 prose-h2:tracking-wide prose-p:text-slate-300 prose-a:text-slate-400 prose-a:w-fit px-3 py-6"><h2>Web development business</h2> <p>Another project in the making. I&#39;m still working on it. It&#39;s a website for my business
				someday, selling web development services in my country. Again, build in Sveltekit and
				TailwindCSS.</p> <a href="https://klikpanet.netlify.app" target="_blank">Visit the site</a></div></div>  <div class="relative flex justify-center gap-3 items-center rounded-r-xl"><div class="absolute w-full h-full -bottom-4 right-12 rounded-xl border-4 border-lime-300 -z-10"></div> <img${add_attribute("src", carsWebsite, 0)} alt="fotonepremicnine.si website" width="480px" height="235px" class="object-cover object-center aspect-video rounded-xl order-2"> <div class="flex flex-col prose max-w-none prose-h2:text-slate-200 prose-h2:tracking-wide prose-p:text-slate-300 prose-a:text-slate-400 prose-a:w-fit px-3 py-6"><h2>Cars exhibition website</h2> <p>This was made for my client from Upwork. I had to build 4 pages for desktop screens only, so
				don&#39;t open them on mobile, please. Pages are build in AstroJS.</p> <a href="https://cars-messe-project.vercel.app/" target="_blank">Visit the site</a></div></div> <div class="flex flex-col max-w-none prose prose-h2:text-slate-100 prose-p:text-slate-200 prose-h3:text-slate-200 prose-a:text-slate-400 prose-a:w-fit py-24"><h2>...and some other honorable mentions:</h2> <div><h3>Presentation website:</h3> <p>A presentation made for a client from Upwork. It&#39;s made only for desktop screens and not for
				smaller mobile screens. It&#39;s made in ReactJS and TailwindCSS. <a href="https://slides-react.vercel.app/" target="_blank">Visit the site</a></p></div> <div><h3>Molecules database website:</h3> <p>This was supposed to be made for a client, but I turned it down, because I didn&#39;t know if I
				can build it. But I build it anyway, just for my sake. This a app that fetches a large
				database of molecules and displays its information. It&#39;s made in ReactJS and TailwindCSS. <a href="https://drug-molecules.vercel.app/" target="_blank">Visit the site</a></p></div> <div><h3>Movies website:</h3> <p>Web app that fetches the movies from database. Made in Svelte and TailwindCSS. <a href="https://movies-app-markoskace1.vercel.app/" target="_blank">Visit the site</a></p></div> <div><h3>Doughnuts website:</h3> <p>I&#39;ve found the design on Figma and really liked it. It&#39; made in ReactJS and TailwindCSS. <a href="https://markoskace1.github.io/doughnuts-react/" target="_blank">Visit the site</a></p></div></div></section>`;
});
export {
  Page as default
};
